pipeline {
  agent {
    node {
      label 'win'&&'slave'
      customWorkspace "workspace\\${JOB_NAME.replace("%2F", "_")}"
    }

  }
  stages {
    stage('Build') { 
      steps {
        

        script{
          DeploymentProperties = readJSON file: "Infrastructure/Jenkins/DeploymentConfig.json"
        }

        wnmp file: "A"

        bat "nuget restore ${DeploymentProperties.SolutionName}"
        bat "\"${tool 'MSBuild'}\" ${DeploymentProperties.SolutionName} /p:Configuration=Release /p:Platform=\"Any CPU\" /p:ProductVersion=1.0.0.${env.BUILD_NUMBER}"
      }
    }
    stage('Test') {
      steps {
        echo 'Testing..'
      }
    }
    stage('Package Artifacts') {
      steps {
        zip(glob: DeploymentProperties.ArtifactsToPack, zipFile: DeploymentProperties.ZipPackageName)
        archiveArtifacts(artifacts: DeploymentProperties.ZipPackageName, onlyIfSuccessful: true, fingerprint: true)
      }
    }
    stage('Push to artifact storage') {
      when {
        branch 'master'
      }
      steps {

        echo "DDD"

      }
    }
    stage('Deploy to Test')
    {
        steps{
          echo "Testing"
        }
    }
    stage('Run smoke tests'){
        steps{
          echo "Testing"
        }
    }
    stage('Run API tests'){
      steps{
        echo "Testing" 
      }
    }
    stage('Run stress tests'){
      steps{
        echo "Testing"
      }
    }
  }
  environment {
    WorkspaceName = JOB_NAME.replace("%2F", "_")
    ABC = "WWW"
    DeploymentProperties = "QQQ"
  }
  options {
    buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    timeout(time: 20, unit: 'MINUTES')
  }
}