pipeline {
  agent {
    node {
      label 'win'&&'slave'
      customWorkspace "workspace\\${JOB_NAME.replace("%2F", "_")}"
    }

  }
  stages {
    stage('Build') { 
      steps {
        echo "B"
        script{
          buildDotNet()
        }
      }
    }
    stage('Test') {
      steps {
        echo "B"
        script{
          testDotNet()
        }
      }
    }
    stage('Package Artifacts') {
      steps {
        script{
          echo "B"
          archivePackage()
        }
      }
    }
    stage('Push to artifact storage') {
      when {
        branch 'master'
      }
      steps {
        script{
          echo "B"
          deployToS3()
        }

      }
    }
    stage('Deploy to Test')
    {
        steps{
          script{
            echo "B"
            pushToEnvironment()
          }
        }
    }
    stage('Run smoke tests'){
        steps{
          script{
            echo "B"
            smokeTestEnvironment()
          }
        }
    }
    stage('Run API tests'){
      steps{
        script{
          echo "B"
          apiTestEnvironment()
        }
      }
    }
    stage('Run stress tests'){
      steps{
        script{
          echo "B"
          stressTestEnvironment()
        }
      }
    }
  }
  environment {
    WorkspaceName = JOB_NAME.replace("%2F", "_")
    ConfigLocation = "Infrastructure/Jenkins/DeploymentConfig.json"
  }
  options {
    buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    timeout(time: 20, unit: 'MINUTES')
  }
}